---
title: "R Notebook"
output: html_notebook
---

```{r}
#ordinate 
ord <- phyloseq::ordinate(ps16S_bac_rarefy_iter, method = "NMDS", distance = "bray", k =3)
#plot ordiantion
phyloseq::plot_ordination(physeq = ps16S_bac_rarefy_iter, ordination = ord) + facet_wrap(~ Timepoint, scales = "free") + geom_point(aes(color = Treatment)) +  theme_bw()  

phyloseq::plot_ordination(physeq = ps16S_bac_rarefy_iter, ordination = ord,) + facet_wrap(~ Treatment, scales = "free", nrow = 2, ncol = 4) + geom_point(aes(color = Timepoint)) +    theme_bw()  


#plot ordiantion
#phyloseq::plot_ordination(physeq = ps16S_bac_rarefy_iter, ordination = ord) + facet_wrap(~ Timepoint, scales = "free") + geom_point(aes(color = Treatment)) +  theme_bw()  
allGroupsColors<- c("grey0", "gray12", "grey24", "grey36", "grey48", "grey60", "grey72", "gray84")

allGroupsColors<- c("#084594", "#2171b5", "#4292c6", "#6baed6", "#9ecae1", "#c6dbef", "#deebf7", "#f7fbff")

ord <- phyloseq::ordinate(ps16S_bac_rarefy_iter, method = "CAP", formula = ~Timepoint + Treatment)
phyloseq::plot_ordination(physeq = ps16S_bac_rarefy_iter, ordination = ord, color = "Timepoint") + facet_wrap(~ Treatment, scales = "free", nrow = 2, ncol = 4)  +    theme_bw()  +   scale_color_manual(values = rev(allGroupsColors))

phyloseq::plot_ordination(physeq = ps16S_bac_rarefy_iter, ordination = ord, color = "Treatment") + facet_wrap(~ Timepoint, scales = "free", nrow = 2, ncol = 4)  +    theme_bw() 





#extract axis scores 
scrs<-vegan::scores(ord)$sites
#add metadata columsn 
scrs <- cbind(as.data.frame(scrs), Treatment = sample_data(ps16S_bac_rarefy_iter)$Treatment)
scrs <- cbind(as.data.frame(scrs), Timepoint = sample_data(ps16S_bac_rarefy_iter)$Timepoint)
#find centroid of treatments by treatment*Timepoint interaction
cent <- aggregate(cbind(NMDS1, NMDS2) ~ Treatment * Timepoint, data = scrs, FUN = mean)
#sort based on Treatment and Timepoint
cent_sorted <- cent[order(cent$Treatment, cent$Timepoint), ]

sample_data(ps16S_bac_rarefy_iter)$trt_tp <- paste(sample_data(ps16S_bac_rarefy_iter)$Treatment,sample_data(ps16S_bac_rarefy_iter)$Timepoint)
physeq_dist<-parallelDist::parDist(as.matrix(data.frame(otu_table(ps16S_bac_rarefy_iter))), method = "bray")
md_bd <- data.frame(sample_data(ps16S_bac_rarefy_iter))

t<-vegan::betadisper(physeq_dist, group = c(md_bd$trt_tp))
disp<-data.frame(t$group.distances)
disp$Treatment_disp <- str_split(rownames(disp), pattern = " ", simplify = T) [,1]
disp$Timepoint_disp <- str_split(rownames(disp), pattern = " ", simplify = T) [,2]

cent_sorted<-cbind(cent_sorted, disp)
cent_sorted$Treatment == cent_sorted$Treatment_disp
cent_sorted$Timepoint == cent_sorted$Timepoint_disp




#append values to scrs df
cent_sorted$trt_tp <- paste(cent_sorted$Treatment, cent_sorted$Timepoint, sep = "_")
scrs$trt_tp <- paste(scrs$Treatment, scrs$Timepoint, sep = "_")
joined_Df<-full_join(scrs, cent_sorted, "trt_tp")

names(joined_Df) <- c( "NMDS1", "NMDS2", "NMDS3", "Treatment.x","Timepoint.x", "trt_tp",  "Treatment.y", "Timepoint.y", "NMDS1_cent", "NMDS2_cent", "group_dispersion", "Treatment_disp", "Timepoint_disp")

View(joined_Df)


#write_csv(cent_sorted, "/Users/gordoncuster/Desktop/Git_projects/ASD/Data/cent_sorted.csv")
#write_csv(scrs, "/Users/gordoncuster/Desktop/Git_projects/ASD/Data/scrs.csv")

```



```{r}
cent_sorted$Treatment <- factor(cent_sorted$Treatment, levels = c("F+W", "F+WM", "CC", "CC+WM", "Tr", "Tr+WM", "2spp", "2spp+WM"), ordered = T)

ggplot(cent_sorted, 
       aes(
          x = NMDS1, 
          y = NMDS2, 
          color = Treatment
       )
)  +
   #facet_wrap(~Treatment, scales = "fixed") +
   geom_path(aes(group = "all",), color = "grey") +
   geom_point(aes(size=t.group.distances)) +
    # geom_text(size = 5, color ="Black", aes(label = Timepoint), position = position_nudge(x = 0.01, y = 0.01)) + 
  geom_text(size = 5, color ="black", aes(label = Timepoint)) + 
   #labs(title = ) +
  facet_wrap(~Treatment, scales = "free", nrow = 2, ncol = 4) +
   theme_bw()  + 
   # I hate that without this 
   # The legend is little "a"s 
   # because we're using geom_text
   # We might not need this at all since the graphs are faceted?
   guides(
      color = guide_legend(
         override.aes = aes(label = "")
      )
   )

ggsave("/Users/gordoncuster/Desktop/Git_projects/ASD/Results/Images/temporal_tracking_centroids.esp", device = "eps", width = 8, height = 6)

ggplot(joined_Df, 
       aes(
          x = NMDS1_cent, 
          y = NMDS2_cent, 
          color = Treatment.x
       )
)  +
   #facet_wrap(~Treatment, scales = "fixed") +
   geom_path(aes(group = "all",), color = "grey") +
   geom_point(aes(size=group_dispersion)) +
    geom_point(aes(x = NMDS1, y = NMDS2, shape = Timepoint.x), alpha = 0.5) + 
  scale_shape_manual(values=1:nlevels(joined_Df$Timepoint.x)) +
    # geom_text(size = 5, color ="Black", aes(label = Timepoint), position = position_nudge(x = 0.01, y = 0.01)) + 
  geom_text(size = 5, color ="grey60", aes(label = Timepoint.x)) + 
   #labs(title = ) +
  facet_wrap(~Treatment.x, scales = "free", nrow = 2, ncol = 4) +
   theme_bw()  + 
   # I hate that without this 
   # The legend is little "a"s 
   # because we're using geom_text
   # We might not need this at all since the graphs are faceted?
   guides(
      color = guide_legend(
         override.aes = aes(label = "")
      )
   )






```





```{r}





cent$Order <- as.integer(as.factor(cent$Timepoint))

cent <- cent[order(cent$Timepoint),]

ggplot(cent, aes(x = NMDS1, y=NMDS2, group = Treatment)) + geom_point(aes(color = Treatment, shape = Timepoint)) +scale_shape_manual(values=1:nlevels(scrs$Timepoint)) + geom_line() 

ggplot(cent, aes(x = NMDS1, y = NMDS2, group = Treatment, color = Treatment, shape = Timepoint)) +
  geom_line() + scale_shape_manual(values=1:nlevels(scrs$Timepoint))+
  geom_point() +
  labs(title = "Line Between Points of a Group") +
  scale_x_continuous(breaks = seq(-0.4, 0.4, by = 0.1), minor_breaks = NULL)



ggplot(cent, aes(x = NMDS1, y = NMDS2, group = Treatment, color = Treatment, shape = Timepoint)) +
  geom_line() +
  geom_point() +
  labs(title = "Line Between Points of a Group") +
  scale_x_continuous(breaks = seq(-0.4, 0.4, by = 0.1), minor_breaks = NULL) +
  scale_shape_manual(values = 1:nlevels(cent$Timepoint))

# Sorting the data by Treatment and Timepoint
cent_sorted <- cent[order(cent$Treatment, cent$Timepoint),]
cent_sorted$Timepoint2 <- as.numeric(gsub("t", "", cent_sorted$Timepoint))
cent_sorted$NextTimepoint <- ave(cent_sorted$Timepoint2, cent_sorted$Treatment, FUN = function(x) c(tail(x, -1), NA))

ggplot(cent_sorted, aes(x = NMDS1, y = NMDS2, group = Timepoint, color = Timepoint)) +
  geom_line(aes(group = paste(Timepoint, NextTimepoint, sep = " to ")), na.rm = TRUE) +
  geom_point() +
  labs(title = "Line Between Points of a Group") +
  scale_x_continuous(breaks = seq(-0.4, 0.4, by = 0.1), minor_breaks = NULL) +
  facet_wrap(~Treatment, scales = "free") 

```


